logstash:
  image: logstash:1.5
  ports:
    - "5000:5000"
  volumes:
    - ./logstash:/etc/logstash.d
  volumes_from:
    - logstashdata
  command: logstash -f /etc/logstash.d/logstash.conf
  links:
    - elasticsearch
elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  image: kibana:4.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch
logstashdata:
  image: busybox
  volumes:
    - /var/logstash
mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=1q9o2w8i37eu
    - MYSQL_DATABASE=database
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=1q9o2w8i37eu
  volumes:
    - ./mysql/etc:/etc/mysql/conf.d/
    - ./mysql/init.d:/docker-entrypoint-initdb.d/
  volumes_from:
    - logstashdata
php:
  build: php
  volumes:
    - ./php/www:/var/www/html
    - ./php/etc:/etc/apache2/conf-enabled/
  volumes_from:
    - logstashdata
  links:
    - mysql
  ports:
    - "80:80"
