logstash:
  image: logstash
  ports:
    - "5000:5000"
  volumes:
    - ./logstash:/etc/logstash.d
  volumes_from:
    - logstashdata
  command: logstash -f /etc/logstash.d/logstash.conf
  links:
    - elasticsearch
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
logstashdata:
  image: busybox
  volumes:
    - /var/logstash
mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=1q9o2w8i37eu
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=1q9o2w8i37eu
  volumes:
    - ./mysql/etc:/etc/mysql/conf.d/
    - ./mysql/init.d:/docker-entrypoint-initdb.d/
  volumes_from:
    - logstashdata
wordpress:
  image: wordpress:4.3.1-apache
  volumes:
    - ./wordpress/www:/var/www/html
    - ./wordpress/etc:/etc/apache2/conf-enabled/
  volumes_from:
    - logstashdata
  links:
    - mysql
  ports:
    - "80:80"
  environment:
    - WORDPRESS_DB_HOST=mysql
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=1q9o2w8i37eu
    - WORDPRESS_DB_NAME=wordpress
